import React, { useState, useRef } from "react";
import "../Authentication.css";

export default function LoginPage({ onLogin, onSignupPage }) {
  const usernameRef = useRef();
  const passwordRef = useRef();
  const [error, setError] = useState(null);

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError(null);

    const username = usernameRef.current.value;
    const password = passwordRef.current.value;

    if (!username) {
      setError("Please enter a valid username.");
      return;
    }
    else if (!password) {
      setError("Incorrect password.");
      return;
    }

    try {
      const res = await fetch("/api/login", { 
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ username, password }),
      });

      if (res.ok) {
        onLogin(username); // This calls onLogin with the correct username
      } else {
        const data = await res.json();
        setError(data.error);
      }
    } catch (err) {
      setError("An unexpected error occurred, Please try again.");
    }
  };
  // Google Gemini was used to assist in writing the UI portion of this code. (Lines 44 to 94) (See below comments for prompts/responses.)
  // The code generated by Google Gemini has been modified to better fit our requirements for this project.
  return (
    <div className="login-container">
      <div className="login-card">
        <h2 className = "login-header">Login</h2>
        <p className="login-subtext">Sign in to continue</p>

        {error && (
          <div className="error-banner">
            {error}
          </div>
        )}

        <form className="login-form">
          <div className="input-group">
            <label className="input-label">
              Username
              <input 
                  type="text" 
                  required 
                  placeholder="Enter username" 
                  className="login-input"
                  ref={usernameRef} 
              />
            </label>
          </div>

          <div className="input-group">
            <label className="input-label">
              Password
              <input 
                  type="password" 
                  required 
                  placeholder="Enter password" 
                  className="login-input"
                  ref={passwordRef} 
              />
            </label>
          </div>

          <button type="submit" onClick={handleSubmit} className="login-button">
              Login
          </button>
        </form>
        <div className="auth-toggle-text">
          Don't have an account?{" "}
          <button className="auth-toggle-link" onClick={onSignupPage}>
            Sign up
          </button>
        </div>
      </div>
    </div>
  );
}

// ============================================================
// Google Gemini was used to assist in writing the UI portion of this code.
// ===========================================================
// PROMPT: 
// ===========================================================
// Role: Act as a diligent expert front-end software engineer. 
// You have expertise in Javascript, React, Node.js, css, 
// design patterns, clean code, and front-end UI. 

// Task: Design the UI portion of a React based login page 
// (the portion that exists in the React function return value). 
// The login page should contain a “Login” header, a box to 
// input a Username, a box to input a Password, a button to submit, 
// and a portion to display errors if the login fails or is invalid. 
// The user-inputted values for username and password should be 
// passed to the variables “username” and “password” only when the 
// submit button is clicked. The error message will be stored in the 
// variable “error” which should be displayed. There should also be 
// a button that calls the function “onSignupPage”, which allows the 
// user to navigate to a signup page if they do not have an account. 
// All the page styles should be stored in a separate css file. 

// Contextual Information: All the logic for the login page has 
// already been coded in React. I have a variable called “username”, 
// a variable called “password”, and a variable called “error”. The 
// function to navigate to the signup page is called “onSignupPage”, 
// and the function to be called on clicking submit is called 
// “handleSubmit”. I value reliability in this situation. 

// Instructions: (1) Plan a clean design, then (2) generate the code 
// to write the program. 

// Before you start your task, ask me any questions you have about 
// important decisions, or requirements. 

// ===========================================================
// RESPONSE:
// ===========================================================

// Hello! As an expert front-end engineer, I am happy to help you 
// build a reliable, clean, and accessible UI for your login page.

// Before we proceed with the design plan and the code generation, 
// I have three specific questions to ensure the implementation 
// integrates perfectly with your existing logic and meets your 
// data flow requirements:

// Input Handling (The "Only on Click" Constraint): You mentioned 
// that values should be passed to your username and password 
// variables only when the submit button is clicked.

// Does your existing logic expect Uncontrolled Components (where 
// we use useRef to grab the value directly from the DOM node upon 
// submission)?

// Or, should I create local temporary state (e.g., localUsername, 
// localPassword) to handle the typing, and then pass those values 
// to your main variables inside handleSubmit?

// Error Variable Structure: To ensure the error box renders 
// correctly, what is the data type of the error variable when 
// there is no error? Is it null, undefined, false, or an empty 
// string ""?

// Visual Style & Layout: For the CSS, do you have a specific 
// aesthetic in mind? (e.g., a centered "Card" style on a 
// full-screen background, a minimalistic flat design, or a 
// specific color scheme?)

// Once you clarify these points, I will outline the design and 
// provide the React JSX and CSS file.

// ===========================================================
// PROMPT: 
// ===========================================================
// 1. The existing logic does not currently expect Uncontrolled 
// Components, but use this method in the code instead of local 
// temporary state.

// 2. The error variable contains null when there is no error.

// 3. A centered Card style on a full-screen background

// ===========================================================
// RESPONSE: 
// ===========================================================

// Thank you for clarifying. Using Uncontrolled Components via 
// useRef is an excellent choice for performance in forms where 
// you don't need to validate every keystroke, and it perfectly 
// aligns with your requirement to only pass data upon submission.

// Here is the design plan and the resulting code implementation.

// 1. Design Strategy
// To ensure reliability and clean code, I have structured the 
// solution as follows:

// Layout Architecture: I will use a Flexbox container for the 
// page background to center the login card perfectly, regardless 
// of screen size.

// Accessibility (A11y):

// I will use a semantic <form> element. This ensures that pressing 
// "Enter" while inside an input box automatically triggers the 
// submit action—a critical UX detail.

// Inputs will be linked to Labels using the htmlFor and id attributes.

// Data Flow (Uncontrolled):

// We will initialize two React Refs (usernameRef and passwordRef).

// We will intercept the native form submission, prevent the 
// default page reload, extract the values from the refs, and then 
// call your handleSubmit.

// Error Handling: The error box will use conditional rendering 
// (error && ...) to ensure the DOM remains clean when no errors 
// exist.

// 2. The Code

// A. The CSS Styles (Login.css)
// This file defines the "Centered Card" aesthetic with a clean, 
// professional look.

// CSS

// /* Login.css */

// /* 1. Page Container - Full screen background and centering */
// .login-container {
//   min-height: 100vh;
//   display: flex;
//   align-items: center;
//   justify-content: center;
//   background-color: #f9fafb;
//   font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
// }

// /* 2. The Card - White box with shadow */
// .login-card {
//   max-width: 28rem;
//   width: 100%;
//   background-color: white;
//   border-radius: 0.75rem;
//   box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05);
//   padding: 2rem;
//   border: 1px solid #f3f4f6;
//   margin: 1rem;
// }

// /* 3. Typography */
// .login-header {
//   font-size: 1.5rem;
//   font-weight: 700;
//   color: #111827;
//   margin-bottom: 0.5rem;
//   margin-top: 0;
// }

// .login-subtext {
//   color: #6b7280;
//   margin-bottom: 1.5rem;
//   margin-top: 0;
// }

// /* 4. Error Box */
// .error-banner {
//   margin-bottom: 1rem;
//   padding: 0.75rem;
//   background-color: #fef2f2;
//   color: #b91c1c;
//   font-size: 0.875rem;
//   border-radius: 0.5rem;
//   border: 1px solid #fecaca;
// }

// /* 5. Form Elements */
// .login-form {
//   display: flex;
//   flex-direction: column;
//   gap: 1.5rem;
// }

// .input-group {
//   display: flex;
//   flex-direction: column;
// }

// .input-label {
//   display: block;
//   font-size: 0.875rem;
//   font-weight: 500;
//   color: #374151;
//   margin-bottom: 0.25rem;
// }

// .login-input {
//   width: 100%;
//   padding: 0.5rem 1rem;
//   border: 1px solid #d1d5db;
//   border-radius: 0.5rem;
//   font-size: 1rem;
//   outline: none;
//   box-sizing: border-box;  /* Ensures padding doesn't break width */
//   transition: border-color 0.2s, box-shadow 0.2s;
//   background-color: #ffffff; /* Explicitly white */
//   color: #111827;
// }

// .login-input:focus {
//   border-color: #2563eb;
//   box-shadow: 0 0 0 3px rgba(37, 99, 235, 0.1);
// }

// /* 6. Buttons */
// .login-button {
//   width: 100%;
//   padding: 0.625rem 1rem;
//   background-color: #2563eb;
//   color: white;
//   font-weight: 500;
//   border-radius: 0.5rem;
//   border: none;
//   cursor: pointer;
//   font-size: 1rem;
//   transition: background-color 0.2s;
// }

// .login-button:hover {
//   background-color: #1d4ed8;
// }

// /* Styles for the toggle link */
// .auth-toggle-text {
//   margin-top: 1.5rem;
//   text-align: center;
//   font-size: 0.875rem;
//   color: #6b7280;
// }

// .auth-toggle-link {
//   color: #2563eb;
//   font-weight: 500;
//   cursor: pointer;
//   background: none;
//   border: none;
//   padding: 0;
//   font: inherit;
//   text-decoration: underline;
// }

// .auth-toggle-link:hover {
//   color: #1d4ed8;
// }

// B. The React Component Logic
// I have included the component definition. Please note the use of useRef to grab the values specifically when onFormSubmit is triggered.

// JavaScript

// import React, { useRef } from 'react';
// import './Login.css'; // Importing the CSS file

// const Login = ({ 
//   // Assuming these are passed as props based on your context
//   handleSubmit, 
//   onSignupPage, 
//   error 
// }) => {
  
//   // 1. Initialize Refs for Uncontrolled Components
//   const usernameRef = useRef(null);
//   const passwordRef = useRef(null);

//   // 2. Local handler to extract values and pass them to your logic
//   const onFormSubmit = (e) => {
//     e.preventDefault(); // Prevent browser refresh

//     // Extract current values strictly on submit click/enter
//     const usernameValue = usernameRef.current.value;
//     const passwordValue = passwordRef.current.value;

//     // Call your existing logic with the extracted values
//     handleSubmit(usernameValue, passwordValue);
//   };

//   return (
//     <div className="login-container">
//      <div className="login-card">
//        <h2 className="login-header">Login</h2>
//        <p className="login-subtext">Sign in to continue to the scheduler.</p>

//        {/* 3. Error Rendering */}
//        {error && (
//          <div className="error-banner">
//            {error}
//          </div>
//        )}

//        <form className="login-form">
//          <div className="input-group">
//            <label className="input-label">
//              Username
//              <input 
//                  type="text" 
//                  required 
//                  placeholder="Enter username" 
//                  className="login-input"
//                  ref={usernameRef} 
//              />
//            </label>
//          </div>

//          <div className="input-group">
//            <label className="input-label">
//              Password
//              <input 
//                  type="password" 
//                  required 
//                  placeholder="Enter password" 
//                  className="login-input"
//                  ref={passwordRef} 
//              />
//            </label>
//          </div>

//          <button type="submit" onClick={handleSubmit} className="login-button">
//              Login
//          </button>
//        </form>

//        <div className="auth-toggle-text">
//          Don't have an account?{" "}
//          <button className="auth-toggle-link" onClick={onSignupPage}>
//            Sign up
//          </button>
//        </div>
//      </div>
//    </div>
//   );
// };

// export default Login;
// Key Implementation Details
// useRef Usage: usernameRef.current.value is accessed only when the login button is clicked. This ensures no re-renders occur while typing, and the data is pulled exactly when requested.

// Required Attributes: Added required to the inputs. This provides immediate browser-native feedback if a user tries to submit an empty form, saving a function call.